# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Mac/Home/Documents/GitHub/EEEE4123/Project/IntMatMulCore/IntMatMulCore.srcs/sources_1/ip/dpram64x32/dpram64x32.xci
# IP: The module: 'dpram64x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Mac/Home/Documents/GitHub/EEEE4123/Project/IntMatMulCore/IntMatMulCore.srcs/sources_1/ip/dpram64x32/dpram64x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpram64x32'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Mac/Home/Documents/GitHub/EEEE4123/Project/IntMatMulCore/IntMatMulCore.srcs/sources_1/ip/dpram64x32/dpram64x32.xci
# IP: The module: 'dpram64x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Mac/Home/Documents/GitHub/EEEE4123/Project/IntMatMulCore/IntMatMulCore.srcs/sources_1/ip/dpram64x32/dpram64x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpram64x32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
