webtalk_init -webtalk_dir C:/Users/eeyaa63/Downloads/EEEE4123/Lab2/Lab2.sim/sim_1/synth/func/xsim/xsim.dir/temp_cond_tb_func_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Feb  9 18:52:35 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174122817_1777582222_210786485_824" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4a6f7e52-5726-4ffa-adf7-466bd80c6916" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "062bd6cfc32e47ba96428d219b0cb70b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i7-11700T @ 1.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1392 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "61 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "11012_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3817665487 -regid "174122817_1777582222_210786485_824" -xml C:/Users/eeyaa63/Downloads/EEEE4123/Lab2/Lab2.sim/sim_1/synth/func/xsim/xsim.dir/temp_cond_tb_func_synth/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/eeyaa63/Downloads/EEEE4123/Lab2/Lab2.sim/sim_1/synth/func/xsim/xsim.dir/temp_cond_tb_func_synth/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/eeyaa63/Downloads/EEEE4123/Lab2/Lab2.sim/sim_1/synth/func/xsim/xsim.dir/temp_cond_tb_func_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
