webtalk_init -webtalk_dir C:/Users/eeyaa63/Documents/GitHub/EEEE4123/Lab2/Lab2.sim/sim_1/synth/func/xsim/xsim.dir/temp_cond_tb_func_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Feb 10 10:32:09 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174122817_1777582222_210786485_824" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1a66b913-0054-4517-ad9f-9efebeb31108" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "062bd6cfc32e47ba96428d219b0cb70b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i7-11700T @ 1.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1392 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "23" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "379 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "12 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "114" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "72" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.55_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "124304_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3250505042 -regid "174122817_1777582222_210786485_824" -xml C:/Users/eeyaa63/Documents/GitHub/EEEE4123/Lab2/Lab2.sim/sim_1/synth/func/xsim/xsim.dir/temp_cond_tb_func_synth/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/eeyaa63/Documents/GitHub/EEEE4123/Lab2/Lab2.sim/sim_1/synth/func/xsim/xsim.dir/temp_cond_tb_func_synth/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/eeyaa63/Documents/GitHub/EEEE4123/Lab2/Lab2.sim/sim_1/synth/func/xsim/xsim.dir/temp_cond_tb_func_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
